import type { Product } from "./types";

export const sampleProducts: Product[] = [
  {
    id: "1",
    name: "Classic White Oxford Shirt",
    description:
      "Premium cotton Oxford shirt, perfect for business and casual wear.",
    price: 59.99,
    category: "Shirts",
    gender: "men",
    color: "White",
    size: "M",
    imageUrl: "https://picsum.photos/seed/shirt1/400/400",
    stock: 45,
    rating: 4.5,
    reviews: 128,
  },
  {
    id: "2",
    name: "Slim Fit Navy Trousers",
    description: "Tailored slim-fit trousers in a versatile navy hue.",
    price: 89.99,
    category: "Pants",
    gender: "men",
    color: "Blue",
    size: "L",
    imageUrl: "https://picsum.photos/seed/pants1/400/400",
    stock: 30,
    rating: 4.3,
    reviews: 87,
  },
  {
    id: "3",
    name: "Leather Chelsea Boots",
    description:
      "Handcrafted full-grain leather Chelsea boots with elastic side panels.",
    price: 199.99,
    category: "Shoes",
    gender: "men",
    color: "Brown",
    size: "42",
    imageUrl: "https://picsum.photos/seed/boots1/400/400",
    stock: 18,
    rating: 4.8,
    reviews: 214,
  },
  {
    id: "4",
    name: "Floral Wrap Dress",
    description: "Elegant floral-print wrap dress in lightweight chiffon.",
    price: 74.99,
    category: "Shirts",
    gender: "women",
    color: "Red",
    size: "S",
    imageUrl: "https://picsum.photos/seed/dress1/400/400",
    stock: 22,
    rating: 4.6,
    reviews: 156,
  },
  {
    id: "5",
    name: "High-Waist Yoga Pants",
    description: "Four-way stretch fabric for maximum comfort and performance.",
    price: 54.99,
    category: "Pants",
    gender: "women",
    color: "Black",
    size: "M",
    imageUrl: "https://picsum.photos/seed/yoga1/400/400",
    stock: 60,
    rating: 4.7,
    reviews: 302,
  },
  {
    id: "6",
    name: "Suede Block Heel Pumps",
    description: "Sophisticated block heel pumps in soft suede leather.",
    price: 129.99,
    category: "Shoes",
    gender: "women",
    color: "Gray",
    size: "39",
    imageUrl: "https://picsum.photos/seed/pumps1/400/400",
    stock: 14,
    rating: 4.4,
    reviews: 93,
  },
  {
    id: "7",
    name: "Canvas Tote Bag",
    description: "Eco-friendly large canvas tote with leather handles.",
    price: 39.99,
    category: "Bags",
    gender: "unisex",
    color: "Brown",
    size: "One Size",
    imageUrl: "https://picsum.photos/seed/tote1/400/400",
    stock: 75,
    rating: 4.2,
    reviews: 67,
  },
  {
    id: "8",
    name: "Leather Crossbody Bag",
    description:
      "Compact leather crossbody with adjustable strap and gold hardware.",
    price: 149.99,
    category: "Bags",
    gender: "women",
    color: "Black",
    size: "One Size",
    imageUrl: "https://picsum.photos/seed/crossbody1/400/400",
    stock: 20,
    rating: 4.9,
    reviews: 178,
  },
  {
    id: "9",
    name: "Stainless Steel Watch",
    description:
      "Minimalist stainless steel watch with sapphire crystal glass.",
    price: 249.99,
    category: "Accessories",
    gender: "unisex",
    color: "Gray",
    size: "One Size",
    imageUrl: "https://picsum.photos/seed/watch1/400/400",
    stock: 12,
    rating: 4.8,
    reviews: 245,
  },
  {
    id: "10",
    name: "Kids Sneakers",
    description: "Lightweight and durable sneakers for active kids.",
    price: 44.99,
    category: "Shoes",
    gender: "kids",
    color: "White",
    size: "33",
    imageUrl: "https://picsum.photos/seed/kidsshoe/400/400",
    stock: 35,
    rating: 4.5,
    reviews: 112,
  },
  {
    id: "11",
    name: "Graphic Print T-Shirt",
    description: "Soft cotton tee with an artistic graphic print.",
    price: 29.99,
    category: "Shirts",
    gender: "unisex",
    color: "Black",
    size: "XL",
    imageUrl: "https://picsum.photos/seed/tshirt1/400/400",
    stock: 80,
    rating: 4.1,
    reviews: 55,
  },
  {
    id: "12",
    name: "Wool Blend Scarf",
    description: "Luxurious wool-blend scarf in a classic herringbone pattern.",
    price: 49.99,
    category: "Accessories",
    gender: "unisex",
    color: "Gray",
    size: "One Size",
    imageUrl: "https://picsum.photos/seed/scarf1/400/400",
    stock: 40,
    rating: 4.3,
    reviews: 78,
  },
  {
    id: "13",
    name: "Slim Chino Pants",
    description: "Versatile slim chino pants, perfect for everyday wear.",
    price: 64.99,
    category: "Pants",
    gender: "men",
    color: "Green",
    size: "M",
    imageUrl: "https://picsum.photos/seed/chino1/400/400",
    stock: 28,
    rating: 4.4,
    reviews: 91,
  },
  {
    id: "14",
    name: "Running Backpack",
    description: "Lightweight hydration-ready backpack for runners and hikers.",
    price: 79.99,
    category: "Bags",
    gender: "unisex",
    color: "Black",
    size: "One Size",
    imageUrl: "https://picsum.photos/seed/backpack1/400/400",
    stock: 33,
    rating: 4.6,
    reviews: 143,
  },
  {
    id: "15",
    name: "Silk Blouse",
    description:
      "Elegant silk blouse with a relaxed fit and button-down front.",
    price: 119.99,
    category: "Shirts",
    gender: "women",
    color: "White",
    size: "S",
    imageUrl: "https://picsum.photos/seed/blouse1/400/400",
    stock: 17,
    rating: 4.7,
    reviews: 189,
  },
  {
    id: "16",
    name: "Gold Hoop Earrings",
    description:
      "Classic 14k gold-plated hoop earrings, lightweight and hypoallergenic.",
    price: 34.99,
    category: "Accessories",
    gender: "women",
    color: "White",
    size: "One Size",
    imageUrl: "https://picsum.photos/seed/earrings1/400/400",
    stock: 55,
    rating: 4.5,
    reviews: 201,
  },
];
